max_steps: 96
env_type: cumulative
variant: both_cvirts
controller: unify
safety_layer: False
in_cap: 500
cost_fn_type: sparse
storage_io_bound: 200

predictions_path: ${hydra:runtime.cwd}/src/data/Dataset10k.csv
prices_path: ${hydra:runtime.cwd}/src/data/gmePrices.npy
shifts_path: ${hydra:runtime.cwd}/src/data/optShift.npy
instances:
  - 2732


iter_init_stats: 10000