max_steps: 96
env_type: cumulative
controller: unify
safety_layer: False
in_cap: 0

predictions_path: ${hydra:runtime.cwd}/src/data/Dataset10k.csv
prices_path: ${hydra:runtime.cwd}/src/data/gmePrices.npy
shifts_path: ${hydra:runtime.cwd}/src/data/optShift.npy
instances:
  - 2732


iter_init_stats: 10000