max_steps: 96
variant: cumulative
controller: unify
safety_layer: False

predictions_path: ${hydra:runtime.cwd}/src/data/Dataset10k.csv
prices_path: ${hydra:runtime.cwd}/src/data/gmePrices.npy
shifts_path: ${hydra:runtime.cwd}/src/data/optShift.npy
instances:
  - 2732


reward_loc: 0
reward_scale: 1
iter_init_stats: 10000