defaults:
  - _self_
  - agent: ppo.yaml
  - wandb: defaults.yaml
  - environment: cumulative.yaml
  - training: defaults.yaml

actor:
  net_spec:
    num_cells: 32
    depth: 2

critic:
  net_spec:
    num_cells: 32
    depth: 2
  constraint_activation: False  # if True, use ReLU activation on the output of the safety critic

seed: 0