algo: "ppolag"
lagrange:
  type: pid
  params:
    initial_value: 5.0
    kp: 0.01
    ki: 0.1
    kd: 0.005
    d_delay: 1
    alpha_p: 0.5
    alpha_d: 0.5
    cost_limit: 0
    proj: "softplus"

actor_lr: 0.01
critic_lr: 0.01
lag_lr: 0.05
schedule: True
schedule_factor: 0.9998

loss_module:
  clip_epsilon: 0.15
  entropy_coef: 0.01
  entropy_bonus: True
  critic_coef: 0.5
  gamma: 0.99
  loss_critic_type: "smooth_l1"
  normalize_advantage: True
  lagrangian_delay: 200

estimator:
  gamma: 0.99
  lmbda: 0.95